//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciKayıtDerssistemi_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminTBL
    {
        public byte adminID { get; set; }
        public string kullaniciAdi { get; set; }
        public string password { get; set; }
    }
}
