//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciKayıtDerssistemi_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlarTBL
    {
        public int ogrenciID { get; set; }
        public Nullable<int> ogrenci { get; set; }
        public Nullable<byte> ders { get; set; }
        public Nullable<decimal> vizeNot { get; set; }
        public Nullable<decimal> finalNot { get; set; }
        public Nullable<decimal> notOrtalaması { get; set; }
        public string gecmeDurumu { get; set; }
    
        public virtual derslerTBL derslerTBL { get; set; }
        public virtual ogrenciTBL ogrenciTBL { get; set; }
    }
}
